### ISSUE TITLE
P5 initializer

### ISSUE THREAD

**Issue by Frostao** [MakeSchool-Tutorials/Intro-Object-Oriented-Programming-Playground#10]
The instruction sates that the initializer should take 2 arguments but the skeleton code only has 1.

**Comment by zontan** [comment]
Also, the skeleton code on P6 assumes a single argument, which doesn't work if you changed it to take 2 arguments (like I did).

I think 2 arguments works better, since that allows you to make favoriteFood a let variable and set it only in Animal's constructor. If you set it in each subclass, then it has to be a var.

**Comment by nikolasburk** [comment]
also, there will be a compiler error further down in the Playground when the initializer of `Animal` takes two arguments, because the `Tiger` class which is declared on line 120 only overrides an initializer that takes one argument `name`. so the compiler complains: 

```
Playground execution failed: P5-Inheritance.xcplaygroundpage:119:14: error: initializer does not override a designated initializer from its superclass
    override init(name: String) {
    ~~~~~~~~ ^
```
